spryker-shop/b2c-demo-marketplace

.scrutinizer.yml
=> Scrutinizer fix

.github/workflows/ci.yml, deploy.ci.acceptance.mariadb.yml, deploy.ci.acceptance.yml
https://spryker.atlassian.net/browse/CC-26175
=> CC-26175: Add robot tests

composer.lock, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.ts, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/nav-overlay/nav-overlay.twig, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/index.ts, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/page-load-state.ts, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/page-load-state/page-load-state.twig, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/search-form/search-form.twig, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/suggest-search/suggest-search.scss, src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.scss, src/Pyz/Yves/ShopUi/Theme/default/styles/helpers/_effect.scss, src/Pyz/Yves/ShopUi/Theme/default/styles/shared.scss, src/Pyz/Yves/ShopUi/Theme/default/templates/page-layout-main/page-layout-main.twig
- Ticket: https://spryker.atlassian.net/browse/CC-25095
- Internal demo shop PR: https://github.com/spryker/b2c-demo-marketplace-internal/pull/258
=> CC-25095 Fixed black screen on page loading.

composer.lock, src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-618
=> SUPESC-618 Added customer access publisher trigger plugin

composer.json, composer.lock, config/Shared/config_default.php, deploy.aop-b2c-testing.yml, deploy.aop-demoshop-b2c.yml, deploy.aws-env-template.yml, deploy.ci.acceptance.mariadb.yml, deploy.ci.acceptance.yml, deploy.ci.api.mariadb.yml, deploy.ci.api.yml, deploy.ci.functional.mariadb.yml, deploy.ci.functional.yml, deploy.dev.yml, deploy.spryker-b2c-eu.yml, deploy.spryker-b2c-intt.yml, deploy.spryker-b2c-intts.yml, deploy.spryker-b2c-production.yml, deploy.spryker-b2c-staging.yml, deploy.spryker-b2c-us.yml, deploy.spryker-b2csec.yml, deploy.spryker-mpb2cintt.yml, deploy.yml
- Ticket: https://spryker.atlassian.net/browse/SUPESC-606
Reference all core PRs for auto-link back-references.
Core PRs
- https://github.com/spryker/spryker/pull/9959
=> SUPESC-606 Fixed filtering by stores in Availability Notifications.

config/Shared/config_default.php
- Ticket: https://spryker.atlassian.net/browse/CC-25997
=> CC-25997 Lowered chunk size for search sync.

tests/PyzTest/Zed/ProductRelation/Presentation/ProductRelationCreateRelationCest.php, tests/PyzTest/Zed/ProductRelation/_support/PageObject/ProductRelationCreatePage.php
- Ticket: https://spryker.atlassian.net/browse/CC-23529
=> CC-23529 Fixed ProductRelationCreateRelationCest test.

composer.lock, package-lock.json, package.json
Ticket: https://spryker.atlassian.net/browse/SUPESC-660
Integration: https://spryker.atlassian.net/browse/CC-26544
=> SUPESC-660 Updated `@spryker/oryx-for-zed` dependency version.

composer.lock
=> Fixed Github actions.

src/Pyz/Zed/EventDispatcher/EventDispatcherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-1208
=> FRW-1208: Integrated redirect response

src/Pyz/Client/ExampleProductSalePage/ExampleProductSalePageDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-28199
=> CC-26834: added missing search plugins.

src/Pyz/Glue/EventDispatcher/EventDispatcherDependencyProvider.php, src/Pyz/Glue/GlueBackendApiApplication/GlueBackendApiApplicationDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-28283
=> CC-28283 Enabled runtime events for Backend API.

composer.json, composer.lock, src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-17164
- Core PR: https://github.com/spryker/spryker/pull/10154
=> CC-17164 Fixed product offer availability when product offer is not assigned to a store.

composer.json, composer.lock, src/Pyz/Client/ProductCategoryStorage/ProductCategoryStorageDependencyProvider.php, src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
- Ticket: https://spryker.atlassian.net/browse/CC-26819
- Core PRs: 
- https://github.com/spryker/suite-nonsplit/pull/1846
- https://github.com/spryker/spryker/pull/7594
- https://github.com/spryker/spryker-shop/pull/791
=> CC-26819 Fixed breadcrumbs for a product integration.

composer.lock, package-lock.json
Ticket: https://spryker.atlassian.net/browse/CC-29330
=> CC-28473 Fixed date-picker validity dates.

src/Pyz/Yves/ShopUi/Theme/default/components/organisms/header/header.twig, src/Pyz/Yves/ShopUi/Theme/default/components/organisms/navigation-top/navigation-top.twig, src/Pyz/Yves/ShopUi/Theme/default/components/organisms/side-drawer/side-drawer.twig, src/Pyz/Yves/StoreWidget/Theme/default/views/switcher/switcher.twig
Ticket: https://spryker.atlassian.net/browse/CC-29246
=> CC-29246 Styling store switcher

.github/workflows/ci.yml, composer.json, composer.lock
Ticket: https://spryker.atlassian.net/browse/SDK-2812
=> SDK-2812: Use evaluator version 0.1.0

composer.lock, src/Pyz/Yves/Form/FormDependencyProvider.php
- IG ticket: https://spryker.atlassian.net/browse/CC-29747
- Main ticket: https://spryker.atlassian.net/browse/CC-26233
=> CC-26233: Improved the address forms 

src/Pyz/Zed/Refund/RefundDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-29900
Core PRs:
- https://github.com/spryker/suite-nonsplit/pull/6908
- https://github.com/spryker/spryker/pull/9471
- https://github.com/spryker/spryker/pull/9892
=> CC-29900 Fixed refund for marketplace integration.

deploy.spryker-mpb2cintt.yml
- Ticket: https://spryker.atlassian.net/browse/CC-29911
=> CC-29911 Adjusted deployment yaml file.

composer.json, composer.lock, src/Pyz/Zed/OauthClient/OauthClientDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/APPS-6512
=> APPS-6512: Auth0 token should be reset when credentials are updated

deploy.spryker-mpb2cintt.yml
- Ticket: https://spryker.atlassian.net/browse/CC-29960
=> CC-29960: Added missing mail sender.

composer.json, composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-29918
=> CC-29918 Fixed AddressForm's city field input type.

composer.json, composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-29931
=> CC-29931 Fixed displaying grand total of merchant order after refund

deploy.spryker-mpb2cintt.yml
- Ticket: https://spryker.atlassian.net/browse/CC-30090
=> CC-30090 Adjust CORS configuration for demo shops GLUE APIs

data/import/common/AT/payment_method_store.csv, data/import/common/DE/payment_method_store.csv, data/import/common/US/payment_method_store.csv, data/import/common/common/payment_method.csv, src/Pyz/Zed/CartsRestApi/CartsRestApiDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-29892
- Core PR: None
=> CC-29892: Fixed payment methods in checkout data

composer.lock, src/Pyz/Client/ProductReview/ProductReviewDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-16486
=> CC-16486 Fixed the self-link for the product review resource.

config/Shared/common/config_oms-development.php, data/import/common/common/glossary.csv, src/Pyz/Glue/CheckoutRestApi/CheckoutRestApiConfig.php, src/Pyz/Glue/PaymentsRestApi/PaymentsRestApiConfig.php, src/Pyz/Shared/CheckoutRestApi/Transfer/checkout_rest_api.transfer.xml, tests/PyzTest/Zed/Console/_data/cli_sandbox/config/Shared/config_default.php
- Ticket: https://spryker.atlassian.net/browse/CC-29892
=> CC-29892: Removed dummy invoice payment from the configuration.

composer.lock, src/Pyz/Zed/Merchant/MerchantDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-30403
- Integration ticket: https://spryker.atlassian.net/browse/CC-30896
=> CC-30403: Added merchant expander bulk plugins execution.

deploy.aop-demoshop-b2c.yml, deploy.ci.acceptance.dynamic-store.yml, deploy.ci.acceptance.mariadb.dynamic-store.yml, deploy.ci.acceptance.mariadb.prefer-lowest.dynamic-store.yml, deploy.ci.acceptance.mariadb.yml, deploy.ci.acceptance.yml, deploy.ci.api.dynamic-store.yml, deploy.ci.api.mariadb.dynamic-store.yml, deploy.ci.api.mariadb.yml, deploy.ci.api.yml, deploy.ci.functional.dynamic-store.yml, deploy.ci.functional.mariadb.dynamic-store.yml, deploy.ci.functional.mariadb.prefer-lowest.dynamic-store.yml, deploy.ci.functional.mariadb.yml, deploy.ci.functional.yml, deploy.dev.dynamic-store.yml, deploy.dev.yml, deploy.dynamic-store.yml, deploy.yml
- Ticket: https://spryker.atlassian.net/browse/SC-15419
=> SC-15419 Integrated the new version of Jenkins into the all public demoshops

composer.lock, src/Pyz/Zed/CheckoutRestApi/CheckoutRestApiConfig.php, src/Pyz/Zed/Shipment/ShipmentConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-31149
=> CC-30986 Disable quote persisting on checkout-data request. 

src/Pyz/Shared/PersistentCart/Transfer/persistent_cart.transfer.xml, src/Pyz/Zed/Quote/QuoteConfig.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-783
=> SUPESC-783 Added missing integration for storing expenses in Quote.

.github/workflows/ci.yml
- Activate NPM checker for critical and high level vulnerabilities in CI
=> Activate NPM checker

composer.json, composer.lock, src/Pyz/Glue/GlueBackendApiApplicationGlueJsonApiConventionConnector/GlueBackendApiApplicationGlueJsonApiConventionConnectorDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-31636
- Core PR: none
=> CC-31636 Add missing image set relationship to concrete product.

config/Shared/config_propel.php
- Ticket: [FRW-6374](https://spryker.atlassian.net/browse/FRW-6374)
- Core PR: - no core PR since it is a clean-up to sync demo-shops
Removed loaderScriptDir property from propel config (to use default)
=> FRW-6374 Removed propel loader script dir property.

.github/workflows/ci.yml
- Ticket: https://spryker.atlassian.net/browse/CC-31641
=> CC-31641 Fixed hosts list and queue fot AT store.

deploy.aop-b2c-testing.yml, deploy.aop-demoshop-b2c.yml
- Ticket: https://spryker.atlassian.net/browse/APPS-10315
=> [APPS-10315] Changed mb2 gateways with domains.

composer.lock, package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-31727
- Core PR: https://github.com/spryker/spryker/pull/10592
=> CC-31727 Update npm dependencies

tests/PyzTest/Glue/Checkout/RestApi/CheckoutDataRelationshipsCest.php, tests/PyzTest/Glue/Checkout/RestApi/CheckoutRestApiCest.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/CheckoutDataServicePointRelationshipsFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/CheckoutDataShipmentRelationshipsFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/CheckoutRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/GuestCheckoutDataRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/GuestCheckoutDataServicePointRelationshipsFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/GuestCheckoutDataShipmentRelationshipsFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/GuestCheckoutRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/ServicePointCheckoutDataRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/ServicePointGuestCheckoutDataRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/ServicePointShipmentTypeCheckoutDataRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/Fixtures/ServicePointShipmentTypeCheckoutRestApiFixtures.php, tests/PyzTest/Glue/Checkout/RestApi/GuestCheckoutDataRelationshipsCest.php, tests/PyzTest/Glue/Checkout/RestApi/ServicePointCheckoutDataRestApiCest.php, tests/PyzTest/Glue/Checkout/RestApi/ServicePointGuestCheckoutDataRestApiCest.php, tests/PyzTest/Glue/Checkout/RestApi/ServicePointShipmentTypeCheckoutDataRestApiCest.php, tests/PyzTest/Glue/Checkout/RestApi/ServicePointShipmentTypeCheckoutRestApiCest.php, tests/PyzTest/Glue/Checkout/_support/CheckoutApiTester.php, tests/PyzTest/Glue/Checkout/codeception.yml
- Ticket: https://spryker.atlassian.net/browse/CC-29651
=> CC-31742 Added C&C checkout tests.

data/import/common/common/glossary.csv
- Ticket: https://spryker.atlassian.net/browse/CC-31781
=> CC-31781 Added missing translation.

src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-31765
=> CC-31765: Added missing plugin to check inactive product offer

deploy.aop-b2c-testing.yml, deploy.aop-demoshop-b2c.yml
- Ticket: https://spryker.atlassian.net/browse/APPS-10665
=> [APPS-10665] Provided enpoints for TF related build.

src/Pyz/Yves/ShopUi/Theme/default/components/molecules/custom-select/custom-select.scss
- Ticket: https://spryker.atlassian.net/browse/CC-31810
=> CC-31810 Fixed header dropdowns

config/install/docker.ci.acceptance.robot.yml, deploy.ci.acceptance.mariadb.robot.yml
- Ticket: https://spryker.atlassian.net/browse/CC-32135
=> CC-32131 Fixed merchant portal and Product configurator build for CI acceptance configuration files.

src/Pyz/Yves/CheckoutPage/Theme/default/components/molecules/summary-sidebar/summary-sidebar.twig, src/Pyz/Yves/CheckoutPage/Theme/default/views/summary/summary.twig, src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail-table/order-detail-table.twig, src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-detail/order-detail.twig, src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/index.ts, src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.scss, src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/shipment-information/shipment-information.twig, src/Pyz/Yves/CustomerReorderWidget/Theme/default/components/molecules/customer-reorder-form/customer-reorder-form.twig, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/action-bar/action-bar.scss, src/Pyz/Zed/Sales/SalesConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-31773
=> CC-31773 Fixed issue with missing shipment price on Order Details page.

composer.lock, src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/merchant-sales-return-create-form/merchant-sales-return-create-form.twig, src/Pyz/Yves/MerchantSalesReturnWidget/Theme/default/components/molecules/separate-returns-by-merchant/separate-returns-by-merchant.ts, src/Pyz/Yves/SalesReturnPage/Theme/default/components/molecules/return-create-form/return-create-form.twig
Ticket: https://spryker.atlassian.net/browse/CC-32186
=> CC-21163 Fixed ability to create return for bundle products.

src/Pyz/Yves/CustomerPage/Theme/default/components/molecules/order-table/order-table.twig, src/Pyz/Yves/ProductAlternativeWidget/Theme/default/views/wishlist-product-alternative/wishlist-product-alternative.twig, src/Pyz/Yves/SalesReturnPage/Theme/default/views/return-list/return-list.twig, src/Pyz/Yves/ShopUi/Theme/default/components/atoms/table/table.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/lazy-image/lazy-image.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/menu/menu.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/status/status.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/index.ts, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.scss, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/table-action-list/table-action-list.twig, src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-detail-table/wishlist-detail-table.twig, src/Pyz/Yves/WishlistPage/Theme/default/components/molecules/wishlist-overview-table/wishlist-overview-table.twig
Ticket: https://spryker.atlassian.net/browse/CC-30070
=> CC-30070 Fixed table actions alignment.

data/import/common/common/product_stock.csv
- Ticket: https://spryker.atlassian.net/browse/CC-32217
=> CC-32217 Fixed Bundle items stock import data.

composer.lock, src/Pyz/Yves/ProductDetailPage/Theme/default/components/molecules/product-carousel/product-carousel.twig, src/Pyz/Yves/ProductImageWidget/Theme/default/components/molecules/image-gallery/image-gallery.twig
Ticket: https://spryker.atlassian.net/browse/CC-32380
=> CC-18186 Fixed color selector on PDP.

composer.lock, src/Pyz/Yves/CustomerPage/CustomerPageDependencyProvider.php, src/Pyz/Yves/Security/SecurityDependencyProvider.php, src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php, src/Pyz/Yves/Validator/ValidatorDependencyProvider.php, src/Pyz/Zed/Application/ApplicationDependencyProvider.php, src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php, src/Pyz/Zed/Security/SecurityDependencyProvider.php, src/Pyz/Zed/Validator/ValidatorDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-5940
=> FRW-5940 Updated spryker to support symfony security modules v6

composer.json, composer.lock
- Ticket: https://spryker.atlassian.net/browse/SDK-5711
=> SDK-5711 Update `evaluator` dependency.

deploy.aop-b2c-testing.yml, deploy.aop-demoshop-b2c.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-2217
=> ACP-2217: Stripe missing domains

deploy.ci.acceptance.mariadb.dynamic-store.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-7420
=> FRW-7420: Fixed build

src/Pyz/Zed/SalesPayment/SalesPaymentDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/SUPESC-676
=> SUPESC-676 Fixed sales payment module to save giftcart properly

config/install/docker.ci.acceptance.dynamic-store.robot.yml, deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
FRW-7454 added new config files for UI CI dynamic multistore
- Ticket: [https://spryker.atlassian.net/browse/FRW-7454]
=> FRW-7454 added new config files for UI CI dynamic multistore

.github/workflows/ci.yml, composer.lock, config/install/docker.ci.acceptance.dynamic-store.yml, deploy.ci.api.mariadb.dynamic-store.robot.yml
- Ticket: [https://spryker.atlassian.net/browse/FRW-7451]
=> FRW-7451 new job for robot api tests dynamic multistore

composer.lock
- Ticket: [https://spryker.atlassian.net/browse/CC-33122]
=> CC-33122 Updated composer.loc file for robot container

src/Pyz/Zed/Discount/DiscountDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-7476
=> FRW-7476: Fixed creating discount.

composer.lock
- Ticket: https://spryker.atlassian.net/browse/ACP-2269
- Updated `spryker/sales`.
- Updated `spryker/sales-payment`.
=> ACP-2269 integration

composer.lock, config/install/docker.ci.acceptance.dynamic-store.robot.yml, config/install/docker.ci.acceptance.dynamic-store.yml, config/install/docker.ci.acceptance.robot.yml, config/install/docker.ci.acceptance.yml, config/install/docker.ci.api.dynamic-store.yml, config/install/docker.ci.api.yml, config/install/docker.yml, tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/PickingListItemsBackendJsonApiFixtures.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/PickingListsBackendJsonApiFixtures.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/Fixtures/StartPickingBackendJsonApiFixtures.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/GetCollectionPickingListsBackendJsonApiCest.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/GetPickingListsBackendJsonApiCest.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/PickingListItemsBackendJsonApiCest.php, tests/PyzTest/Glue/PickingListsBackend/JsonApi/StartPickingBackendJsonApiCest.php, tests/PyzTest/Glue/PickingListsBackend/_support/PickingListsBackendApiTester.php, tests/PyzTest/Glue/PickingListsBackend/codeception.yml
- Ticket: https://spryker.atlassian.net/browse/CC-32771
=> CC-32771 Added tests for picking lists BAPI endpoints.

deploy.ci.acceptance.mariadb.dynamic-store.robot.yml
СС-33164 added configurator settings into yml file
Overview
Ticket: https://spryker.atlassian.net/browse/CC-33164
=> СС-33164 added configurator settings into yml file 

composer.json, composer.lock, data/import/common/common/glossary.csv, src/Pyz/Zed/Console/ConsoleDependencyProvider.php, src/Pyz/Zed/Synchronization/SynchronizationDependencyProvider.php
Tickets: 
- https://spryker.atlassian.net/browse/FRW-7452
- https://spryker.atlassian.net/browse/FRW-7291
- https://spryker.atlassian.net/browse/FRW-7432
- https://spryker.atlassian.net/browse/SUPESC-813
- https://spryker.atlassian.net/browse/SUPESC-808
- https://spryker.atlassian.net/browse/FRW-7463
- https://spryker.atlassian.net/browse/FRW-7477
- https://spryker.atlassian.net/browse/FRW-7329
- https://spryker.atlassian.net/browse/FRW-6955
=> FRW-6879 Integration

deploy.ci.acceptance.mariadb.dynamic-store.robot.yml, deploy.dev.dynamic-store.yml, deploy.dynamic-store.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-6380
=> FRW-6380 Adjusted deploy config.

config/install/docker.ci.acceptance.dynamic-store.robot.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-6380
=> FRW-6380 configurable products are broken for robot

composer.lock, data/import/common/common/glossary.csv
- Ticket: https://spryker.atlassian.net/browse/FRW-7821
=> FRW-7296 Integration

src/Pyz/Client/ProductStorage/ProductStorageDependencyProvider.php
Ticket: https://spryker.atlassian.net/browse/CC-33418
=> CC-33418 Fixed configurable product price displaying.

src/Pyz/Yves/ProductReviewWidget/Theme/default/components/molecules/rating-selector/rating-selector.ts
closes [CC-33525](https://spryker.atlassian.net/browse/CC-33525)
=> CC-33525: Fixed rating interaction inside popup

src/Pyz/Zed/Product/ProductConfig.php
Decreased `ProductUpdated` message size by decreasing the number of products sent in one message.
- Ticket: https://spryker.atlassian.net/browse/ACP-49
=> ACP-49: decreased `ProductUpdated` message size

composer.json, composer.lock
- Ticket: https://spryker.atlassian.net/browse/CC-33600
=> CC-33600: Added fallback for concrete product name in MP dashboard.

.github/workflows/robot-ui-e2e-tests.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33768
=> CC-33768: Added fixes for the "Robot Regression UI E2E" 

src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.ts, src/Pyz/Yves/ShopUi/Theme/default/components/molecules/quantity-counter/quantity-counter.twig
Fix behavior while submit quantity on async cart
https://spryker.atlassian.net/browse/CC-33794
=> CC-33794: Fix behavior while submit quantity on async cart

composer.lock, package-lock.json
Updated `composer.lock` with new cypress-tests hash.
=> Enabled cypress tests for epic - Async Cart reload feature.

.github/workflows/enforce-labels.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33917
=> enforce e2e label

composer.json, composer.lock, package-lock.json, tests/PyzTest/Zed/TestifyBackendApi/codeception.dynamic.fixtures.yml
- Ticket: https://spryker.atlassian.net/browse/CC-33999
=> Fixed issues with Commission integration.

public/MerchantPortal/redirect.php
=> ACP-3675: Update redirect.php

.github/workflows/robot-ui-e2e-tests.yml
- Ticket: https://spryker.atlassian.net/browse/CC-34144
=> CC-34144: Adjusted GA workflow.

composer.lock
Tickets:
- CC-34071
- ACP-3677
=> MP payment transfers with commission fixes for OMS (patches)

composer.lock, src/Pyz/Zed/MerchantPortalApplication/Communication/MerchantPortalApplicationCommunicationFactory.php, src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationConfig.php
- Ticket:  https://spryker.atlassian.net/browse/FRW-8932
=> FRW-8932 Marketplace homepage fix integration.

config/Zed/navigation.xml, deploy.aop-b2c-testing.yml, deploy.aop-demoshop-b2c.yml
=> BUGFIX: Fixed PHP version for ACP

composer.lock, src/Pyz/Zed/MerchantCommission/MerchantCommissionConfig.php
- Ticket: https://spryker.atlassian.net/browse/CC-34500
=> CC-34500 Adjusted merchant commission calculation to not rely on price mode per store configuration.

composer.lock, src/Pyz/Zed/MerchantGui/MerchantGuiDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/FRW-9176
=> FRW-9176 Integration.

composer.lock, src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php, src/Pyz/Zed/ProductStorage/Persistence/ProductStoragePersistenceFactory.php
Tickets:
- https://spryker.atlassian.net/browse/FRW-1877
- https://spryker.atlassian.net/browse/SUPESC-866
- https://spryker.atlassian.net/browse/SUPESC-858
- https://spryker.atlassian.net/browse/FRW-9132
- https://spryker.atlassian.net/browse/FRW-8906
=> FRW-9030 Integrations part 5

composer.json, composer.lock, package-lock.json, src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.scss, src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig, src/Pyz/Yves/CatalogPage/Theme/default/templates/page-layout-catalog/page-layout-catalog.twig, tsconfig.mp.json
- Ticket: https://spryker.atlassian.net/browse/CC-34672
=> CC-34672 Collapsible category tree integraton

deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml
- Fixed performance issue in deploy file used by NightCI 
- enabled caching
- upgraded PHP version
=> Fixed deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml performance issues.

config/install/ci.yml, config/install/development.yml, config/install/testing.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9241
=> FRW-9241 Adjusted installation configs.

composer.lock, package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-34731
=> CC-34731 Update Summernote dependency

.robot/Dockerfile, composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-9423
- Core PR: https://github.com/spryker/spryker/pull/11212
=> FRW-9423 Fixed twig error for product view in Merchant Portal.

deploy.aop-demoshop-b2c.yml
- Ticket:  https://spryker.atlassian.net/browse/ACP-4427
=> ACP-4427: Enabled DMS for ACP

composer.json, composer.lock, config/Shared/config_default.php, data/import/common/common/glossary.csv, src/Pyz/Glue/GlueApplication/GlueApplicationConfig.php, src/Pyz/Glue/GlueApplication/GlueApplicationDependencyProvider.php, src/Pyz/Yves/CartPage/Theme/default/components/molecules/cart-summary/cart-summary.twig, src/Pyz/Yves/CheckoutPage/CheckoutPageConfig.php, src/Pyz/Yves/CheckoutPage/CheckoutPageDependencyProvider.php, src/Pyz/Yves/PaymentAppWidget/PaymentAppWidgetConfig.php, src/Pyz/Yves/Router/RouterDependencyProvider.php, src/Pyz/Yves/ShopApplication/ShopApplicationDependencyProvider.php, src/Pyz/Zed/Cart/CartDependencyProvider.php, src/Pyz/Zed/Checkout/CheckoutDependencyProvider.php, src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php, src/Pyz/Zed/Payment/PaymentDependencyProvider.php, src/Pyz/Zed/PaymentApp/PaymentAppDependencyProvider.php, src/Pyz/Zed/PaymentAppShipment/PaymentAppShipmentConfig.php, src/Pyz/Zed/PaymentCartConnector/PaymentCartConnectorConfig.php
- Ticket: https://spryker.atlassian.net/browse/ACP-4588
- Core PR: https://github.com/spryker-shop/suite/pull/1642
=> ACP-4455: Express checkout infrastructure integration.

src/Pyz/Service/DataExport/DataExportDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/CC-34874
=> CC-34874 Fixed Merchant Commission export

src/Pyz/Yves/ProductDetailPage/Theme/default/views/pdp/pdp.twig
https://spryker.atlassian.net/browse/ACP-4626
=> ACP-4516: Fix product data for algolia events

deploy.aop-b2c-testing.yml
- Ticket: https://spryker.atlassian.net/browse/ACP-4378
=> ACP-4378: Fixed url for acp build

.github/workflows/ci.yml, deploy.ci.api.mariadb.robot.yml
- Ticket: https://spryker.atlassian.net/browse/FRW-9599
=> FRW-9599: fix hackaton robot tests

composer.lock, config/Shared/config_default-docker.dev.php, config/Shared/config_default.php, src/Pyz/Zed/MerchantPortalApplication/MerchantPortalApplicationDependencyProvider.php, src/Pyz/Zed/SecurityMerchantPortalGui/SecurityMerchantPortalGuiConfig.php
- Ticket: https://spryker.atlassian.net/browse/FRW-9299
=> FRW-9299 Integrated Profiler enabling.

composer.lock
- Ticket: https://spryker.atlassian.net/browse/SUPESC-897
- https://release.spryker.com/release/pull-request/11247
=> SUPESC-897 Improved performance of BundledProductTable.

deploy.spryker-acb2cmpeu.yml
=> Renamed deploy file + new endpoints

composer.lock, src/Pyz/Zed/ZedNavigation/ZedNavigationConfig.php
- Tickets: 
- https://spryker.atlassian.net/browse/SUPESC-942
- https://spryker.atlassian.net/browse/SUPESC-941
=> SUPESC-942 + SUPESC-942 Merchant Portal performance improvements.

src/Pyz/Yves/CustomerPage/Theme/default/views/profile/profile.twig
- Ticket: https://spryker.atlassian.net/browse/FRW-10067
=> FRW-10067 Added CustomerEmailChangeRequestWidget widget

composer.lock, package-lock.json
- Tickets: https://spryker.atlassian.net/browse/CC-34127, https://spryker.atlassian.net/browse/SUPESC-812
=> CC-34127 Added CSRF param to Company Role User form. 

composer.lock, src/Pyz/Zed/Sales/SalesConfig.php
- Ticket:https://spryker.atlassian.net/browse/CC-22722
=> CC-22722: Order Sequence Generation integration

tests/PyzTest/Zed/CmsGui/Presentation/CmsGuiCreatePageCest.php, tests/PyzTest/Zed/CmsGui/_support/CmsGuiPresentationTester.php
- Ticket: https://spryker.atlassian.net/browse/CC-35490
Improvements
- Fixed CmsGuiCreatePageCest
=> CC-35490 Fixed flaky CMS page test

.github/actions/job-slack-notifications/action.yml
- Ticket: https://spryker.atlassian.net/browse/CC-35773
=> CC-35773 Improved notification on failed github action jobs.

src/Pyz/Yves/AgentPage/AgentPageConfig.php, tests/PyzTest/Zed/ProductOption/Business/ProductOptionFacadeAggregatorTest.php
=> CC-35509: trigger CI

config/install/destructive.yml
- Ticket: https://spryker.atlassian.net/browse/CC-35103
IMPORTANT: These changes should never be merged into master, only into the master-deploy branch.
- Added schedule price application and publish and sync into the destructive deployment to avoid flaky tests.
=> CC-35103 Added Apply Scheduled Price and P&S  into destructive deployment.

.github/workflows/ci.yml, .github/workflows/robot-ui-e2e-tests.yml, deploy.ci.acceptance.dynamic-store-off.yml, deploy.ci.acceptance.mariadb.cypress.yml, deploy.ci.acceptance.mariadb.dynamic-store-off.cypress.yml, deploy.ci.acceptance.mariadb.dynamic-store-off.robot.yml, deploy.ci.acceptance.mariadb.dynamic-store-off.yml, deploy.ci.acceptance.mariadb.prefer-lowest.yml, deploy.ci.acceptance.mariadb.robot.yml, deploy.ci.acceptance.mariadb.yml, deploy.ci.acceptance.yml, deploy.ci.api.dynamic-store-off.yml, deploy.ci.api.mariadb.dynamic-store-off.yml, deploy.ci.api.mariadb.robot.yml, deploy.ci.api.mariadb.yml, deploy.ci.api.yml, deploy.ci.functional.dynamic-store-off.yml, deploy.ci.functional.mariadb.dynamic-store-off.yml, deploy.ci.functional.mariadb.prefer-lowest.yml, deploy.ci.functional.mariadb.yml, deploy.ci.functional.yml
- Tickets: https://spryker.atlassian.net/browse/CC-35872, https://spryker.atlassian.net/browse/CC-35922
=> Enabled composer cache for CI jobs.

composer.lock, package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-35578
=> CC-35578: Fixed Gift Card email templates.

composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-10501
Tests do **not** run automatically on every PR.
To trigger the required test suites, please add the appropriate label(s) to your PR.
For the full list of labels and their associated tests, see our Confluence page: [CI Test Labels & Triggers](https://spryker.atlassian.net/wiki/spaces/Framework/pages/4715216905/Using+PR+labels+to+control+CI+runs+for+project+repositories)
=> FRW-10501: Integration.

deploy.spryker-b2cmp-staging.yml
- Ticket: https://spryker.atlassian.net/browse/SC-22955
=> SC-22955: Added deploy file for staging env with DMS on

deploy.spryker-b2cmp.yml
- Ticket: https://spryker.atlassian.net/browse/SC-22955
=> SC-22955: Renamed deploy file, changed DB name

package-lock.json
- Ticket: https://spryker.atlassian.net/browse/CC-36096
=> CC-36096: Fixes security issue with node modules

composer.lock
- Ticket: https://spryker.atlassian.net/browse/FRW-10772
=> FRW-10776 Integration.

src/Pyz/Yves/CatalogPage/Theme/default/components/molecules/filter-category/filter-category.twig, src/Pyz/Yves/StoreWidget/Theme/default/views/switcher/switcher.twig
- Ticket: https://spryker.atlassian.net/browse/FRW-10760
Updated URL handling in the `filter-category.twig`.
Tests do **not** run automatically on every PR.
To trigger the required test suites, please add the appropriate label(s) to your PR.
For the full list of labels and their associated tests, see our Confluence page: [CI Test Labels & Triggers](https://spryker.atlassian.net/wiki/spaces/Framework/pages/4715216905/Using+PR+labels+to+control+CI+runs+for+project+repositories)
=> FRW-10760 Fixed 404 error on filter by category in dynamic sale category

composer.lock
Ticket: https://spryker.atlassian.net/browse/CC-36115
=> CC-36115 Integrated bugfixes.

composer.lock, config/Shared/config_default.php, config/Zed/cronjobs/jenkins.php, src/Pyz/Client/Catalog/CatalogDependencyProvider.php, src/Pyz/Client/CmsPageSearch/CmsPageSearchDependencyProvider.php, src/Pyz/Zed/MessageBroker/MessageBrokerDependencyProvider.php, src/Pyz/Zed/Publisher/PublisherDependencyProvider.php
- Ticket: https://spryker.atlassian.net/browse/ACP-5354
=> ACP-5354: Algolia: global search to CMS and docs integration
